### ISSUE TITLE
[BUG] OceanFSM causing build to fail

### ISSUE THREAD

**Issue by kiraio-moe** [Macawls/OceanFSM#9]
Unity will fail to build the project because OceanFSM trying to include Editor code into Runtime by selecting the Platforms at `OceanFSM.Editor` Assembly Definition to `Any Platform` instead of only `Editor`.

**Comment by Macawls** [comment]
Fixed by d673bc6dfa0dde8e29b5cef282151cda674f69d4 thank you @kiraio-moe 😄

**Comment by kiraio-moe** [comment]
> Fixed by [d673bc6](https://github.com/Macawls/OceanFSM/commit/d673bc6dfa0dde8e29b5cef282151cda674f69d4) thank you @kiraio-moe 😄

Your welcome :)
Also thanks for such an amazing package! It's help me implement State Machine easily without doing it from scratch. Seriously, it's a pain 😣
